version: '3'
services:
  database:
    image: mysql:5.7
    command:
      - '--character-set-server=utf8'
      - '--collation-server=utf8_unicode_ci'
    ports:
      - '${LOCAL_DB_PORT}:3306'
    restart: on-failure:5
    container_name: '${PRODUCTION_NAME}_db'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./config/database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
  wordpress:
    depends_on:
      - database
    build:
      context: ./config/wordpress
    container_name: '${PRODUCTION_NAME}_wordpress'
    ports:
      - '${LOCAL_SERVER_PORT}:80'
    restart: on-failure:5
    working_dir: /var/www/html/project/public/wp
    volumes:
      - ./config/wordpress/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./config/wordpress/php.ini:/usr/local/etc/php/php.ini
      - ./config/wordpress/xdebug.ini:/usr/local/etc/php/xdebug.ini
      - ./project:/var/www/html/project
    environment:
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_HOST: database:3306
      WP_ENV: development
      PLUGIN_ACF_KEY: '${PLUGIN_ACF_KEY}'
  wordmove:
    tty: true
    depends_on:
      - wordpress
    image: welaika/wordmove
    restart: on-failure:5
    working_dir: /home
    container_name: '${PRODUCTION_NAME}_wordmove'
    volumes:
      - ./config/wordmove:/home/
      - ~/.ssh:/root/.ssh
      - ./project:/var/www/html/project
    environment:
      RUBYOPT: '-EUTF-8'
      LOCAL_SERVER_PORT: '${LOCAL_SERVER_PORT}'
      PRODUCTION_URL: '${PRODUCTION_URL}'
      PRODUCTION_DIR_PATH: '${PRODUCTION_DIR_PATH}'
      PRODUCTION_DB_NAME: '${PRODUCTION_DB_NAME}'
      PRODUCTION_DB_USER: '${PRODUCTION_DB_USER}'
      PRODUCTION_DB_PASSWORD: '${PRODUCTION_DB_PASSWORD}'
      PRODUCTION_DB_HOST: '${PRODUCTION_DB_HOST}'
      PRODUCTION_DB_PORT: '${PRODUCTION_DB_PORT}'
      PRODUCTION_SSH_HOST: '${PRODUCTION_SSH_HOST}'
  mailhog:
    image: mailhog/mailhog
    container_name: '${PRODUCTION_NAME}_mailhog'
    ports:
      - '${LOCAL_SMTP_PORT}:1025' # smtp server
      - '${LOCAL_MAILHOG_PORT}:8025' # web ui
