version: '3'
services:
  database:
    container_name: '${PRODUCTION_NAME}_database'
    image: mysql:5.7
    command:
      - '--character-set-server=utf8'
      - '--collation-server=utf8_unicode_ci'
    ports:
      - '${LOCAL_DB_PORT}:3306'
    restart: on-failure:5
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
  wordpress:
    container_name: '${PRODUCTION_NAME}_wordpress'
    depends_on:
      - database
    build:
      context: ./docker/wordpress
    tty: true
    restart: always
    ports:
      - '${LOCAL_SERVER_PORT}:80'
    restart: on-failure:5
    working_dir: /var/www/html/web/public/wp
    volumes:
      - ./config/wordpress/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./config/wordpress/php.ini:/usr/local/etc/php/php.ini
      - ./web/mu-plugins:/var/www/html/web/mu-plugins
      - ./web/public/wp-config.php:/var/www/html/web/public/wp-config.php
      - ./theme:/var/www/html/web/themes/jun-child
      - ./web/composer.json:/var/www/html/web/composer.json
      - ./web/composer.lock:/var/www/html/web/composer.lock
      - ./web/phpcs.xml:/var/www/html/web/phpcs.xml
      - ./web/setup.sh:/var/www/html/web/setup.sh
      - ./web/wp-cli.yml:/var/www/html/web/wp-cli.yml
    environment:
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_HOST: database:3306
      WP_ENV: development
      TZ: Asia/Tokyo
  phpmyadmin:
    container_name: '${PRODUCTION_NAME}_phpmyadmin'
    depends_on:
      - database
    image: phpmyadmin
    restart: always
    ports:
      - '${LOCAL_PMA_PORT}:80'
    environment:
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      PMA_HOST: database:3306
      PMA_ARBITRARY: 1
  mailhog:
    container_name: '${PRODUCTION_NAME}_mailhog'
    image: mailhog/mailhog
    ports:
      - '${LOCAL_SMTP_PORT}:1025' # smtp server
      - '${LOCAL_MAILHOG_PORT}:8025' # web ui
volumes:
  db_data:
