global:
  sql_adapter: default

local:
  vhost: "http://localhost:<%= ENV['LOCAL_SERVER_PORT'] %>"
  wordpress_path: '/var/www/html/project/public'
  database:
    name: 'wordpress'
    user: 'wordpress'
    password: 'wordpress'
    host: 'database'
    port: 3306
    mysqldump_options: '--default-character-set=utf8 --no-tablespaces'
  paths:
    wp_config: 'wp-config.php'
    wp_content: 'wp/wp-content'
    uploads: 'wp/wp-content/uploads'
    plugins: 'wp/wp-content/plugins'
    mu_plugins: 'wp/wp-content/mu-plugins'
    themes: 'wp/wp-content/themes'
    languages: 'wp/wp-content/languages'

production:
  vhost: "<%= ENV['PRODUCTION_URL'] %>"
  wordpress_path: "<%= ENV['PRODUCTION_DIR_PATH'] %>"
  database:
    name: "<%= ENV['PRODUCTION_DB_NAME'] %>"
    user: "<%= ENV['PRODUCTION_DB_USER'] %>"
    password: "<%= ENV['PRODUCTION_DB_PASSWORD'] %>"
    host: "<%= ENV['PRODUCTION_DB_HOST'] %>"
    port: "<%= ENV['PRODUCTION_DB_PORT'] %>"
    mysqldump_options: '--default-character-set=utf8 --max_allowed_packet=50MB'
  paths:
    wp_config: 'wp-config.php'
    wp_content: 'wp/wp-content'
    uploads: 'wp/wp-content/uploads'
    plugins: 'wp/wp-content/plugins'
    mu_plugins: 'wp/wp-content/mu-plugins'
    themes: 'wp/wp-content/themes'
    languages: 'wp/wp-content/languages'
  exclude:
    - '.git/'
    - '.gitignore'
    - '.gitmodules'
    - '.env'
    - 'node_modules/'
    - 'bin/'
    - 'tmp/*'
    - 'Gemfile*'
    - 'Movefile'
    - 'movefile'
    - 'movefile.yml'
    - 'movefile.yaml'
    - 'wp-content/*.sql.gz'
    - '*.orig'
    - 'wp-content/uploads/backwpup*/*'
    - '.htaccess'
  ssh:
    host: "<%= ENV['PRODUCTION_SSH_HOST'] %>"
    rsync_options: '--verbose'
